"use client";
import { useEffect } from "react";

import Navbar from "@/componants/Navbar";
import Footer from "@/componants/Footer";
import "bootstrap/dist/css/bootstrap.css";
import Home from "@/pages/home";
import "@/styles/globals.css";
// import AOS from 'aos';
// import 'aos/dist/aos.css';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ Component, pageProps }) {
  useEffect(() => {
    // AOS.init();
    if (typeof window !== "undefined") {
      require("bootstrap/dist/js/bootstrap.min.js");
    }
  }, []);

  return (
    <html >
      <body>
        <Navbar />
        
        <Component {...pageProps} />
        <Footer />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
        <script
          type="text/javascript"
          src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
        ></script>
      </body>
    </html>
  );
}
