"use client";
import { useEffect } from "react";

import Navbar from "@/componants/Navbar";
import Footer from "@/componants/Footer";
import "bootstrap/dist/css/bootstrap.css";
import Home from "@/pages/home";
import "@/styles/globals.css";
// import AOS from 'aos';
// import 'aos/dist/aos.css';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ Component, pageProps }) {
  useEffect(() => {
    // AOS.init();
    if (typeof window !== "undefined") {
      require("bootstrap/dist/js/bootstrap.min.js");
    }
  }, []);

  return (
    <html >
      <body>
        <Navbar />
        
        <Component {...pageProps} />
        <Footer />
      
      </body>
    </html>
  );
}
